
services:

  app:
    build: .
    container_name: M614Proyecto
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: db_institut
      DB_USERNAME: alex
      DB_PASSWORD: alex

  db:
    image: mysql:8
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_institut
      MYSQL_USER: alex
      MYSQL_PASSWORD: alex
    ports:
    # Cambie de puerto porque el puerto 3306 a 3307 
      - "3307:3306"

    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: